### ISSUE TITLE
Añadir reglas de protección a las ramas

### ISSUE THREAD

**Issue by acorbacho** [acorbacho/Proyecto_3enRaya#9]
Para evitar pushes en ramas incorrectas, sería interesante programar reglas de protección en ramas. https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by damiancastelao** [comment]
Interesante cuestión, podía estar bien experimentar con alguna regla.
